import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Tech Trade | All Products Page",
  description: "Generated by create next app",
};

const ProductsPage = () => {
    return (
        <div>
            all products
        </div>
    );
};

export default ProductsPage;