//path: src/lib/featuresProductsConstants.ts

export const FeaturesProducts = [
  // 1 Phone
  {
    title: "iPhone 16 Pro",
    slug: "iphone-16-pro",
    key_features: ["Face ID", "Triple Camera", "5G Support"],
    description: "Latest iPhone with advanced camera and performance.",
    banner: "/products/phone/Iphone16-cover.png",
    images: [
      "/products/phone/Iphone16-image1.png",
      "/products/phone/Iphone16-image2.jpg",
    ],
    category: "phone",
    brand: "Apple",
    product_model: "iPhone 14 Pro",
    price: 1099,
    stock: 50,
    warranty: "1 year",
    specs: {
      display: { size: "6.1 inch", type: "OLED", resolution: "2532x1170" },
      processor: { chipset: "A16 Bionic", cpu_type: "Hexa-core" },
      memory: { ram: "6GB", storage: "128GB" },
      camera: { rear: "48MP+12MP+12MP", front: "12MP" },
      battery: { capacity: "3200mAh" },
      connectivity: {
        network: ["5G", "4G"],
        wifi: "802.11ax",
        bluetooth: "5.3",
        ports: ["Lightning"],
      },
      os: "iOS 16",
    },
  },

  // 2 Laptop
  {
    title: "ASUS ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    description: "High-performance gaming laptop.",
    key_features: ["165Hz Display", "RTX 4070"],
    banner: "/products/laptop/laptop_cover_image.jpg",
    images: [
      "/products/laptop/laptop_image1.png",
      "/products/laptop/laptop_image3.png",
    ],
    category: "laptop",
    brand: "ASUS",
    product_model: "G14-2024",
    price: 1899,
    stock: 10,
    warranty: "1 Year",
    specs: {
      processor: {
        brand: "AMD",
        chip_model: "Ryzen 9",
        generation: "3rd gen",
        cores: 8,
        threads: 16,
        speed: "4.0GHz",
      },
      display: {
        size: "14 inch",
        type: "OLED",
        resolution: "2.5K",
        refresh_rate: "165Hz",
        brightness: "200 neds",
      },
      memory: {
        ram: "32GB",
        type: "DDR5",
        speed: "4800MHz",
        slots: 2,
        max: "64GB",
      },
      storage: {
        type: "SSD",
        capacity: "1TB",
        interface: "NVMe",
      },
      graphics: {
        type: "dedicated",
        chip_model: "RTX 4070",
        memory: "8GB",
      },
      ports: { usb: ["USB-C"], hdmi: "2.1", audio: "Jack" },
      battery: { capacity: "76Wh" },
      os: "Windows 11",
    },
  },

  // 3 Gaming Console
  {
    title: "PlayStation 5 Slim",
    slug: "playstation-5-slim",
    description:
      "Experience lightning-fast loading with an ultra-high speed SSD and deeper immersion with support for haptic feedback.",
    key_features: [
      "4K-TV Gaming",
      "Ultra-High Speed SSD",
      "Ray Tracing Support",
    ],
    banner: "/products/console/ps5-cover-image.png",
    images: [
      "/products/console/ps5-image1.png",
      "/products/console/ps5-image2.png",
      "/products/console/ps5-image3.png",
    ],
    category: "gaming_console",
    brand: "Sony",
    product_model: "CFI-2000",
    price: 499.99,
    stock: 45,
    warranty: "1 Year Official",
    specs: {
      processor: {
        chipset_type: "AMD Ryzen Zen 2",
        cores: 8,
        speed: "3.5 GHz",
      },
      memory: {
        ram: "16GB GDDR6",
        storage: "1TB Custom SSD",
        storage_type: "NVMe",
      },
      graphics: {
        chip_model: "AMD Radeon RDNA 2",
        memory: "Variable",
      },
      resolution: ["4K", "1440p", "1080p"],
      frame_rate: "120fps",
      hdr: true,
      ray_tracing: true,
      backward_compatibility: true,
      vr_support: true,
      disc_drive: true,
      ports: ["HDMI 2.1", "USB-C", "USB-A", "Gigabit Ethernet"],
      wifi: "Wi-Fi 6",
      bluetooth: "5.1",
    },
  },

  // 4 Headphone
  {
    title: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    description:
      "Premium wireless noise-cancelling headphones with crystal clear sound and long battery life.",
    key_features: [
      "Active Noise Cancellation",
      "30 Hours Battery",
      "Fast Charging",
      "Touch Controls",
    ],
    banner: "/products/headphone/headphone-image1.png",
    images: [
      "/products/headphone/headphone-image1.png",
      "/products/headphone/headphone-image2.png",
      "/products/headphone/headphone-image3.png",
    ],
    category: "headphone",
    brand: "Sony",
    product_model: "WH-1000XM5",
    price: 399.99,
    stock: 30,
    warranty: "1 Year Official",
    specs: {
      form_factor: "over-ear",
      connectivity: "wireless",
      driver_size: "30mm",
      frequency_response: "4Hz - 40kHz",
      impedance: "48 ohms",
      sensitivity: "102 dB",
      microphone: true,
      noise_cancellation: true,
      battery_life: "30 hours",
      charging_time: "3 hours",
      cable_length: "1.2m",
      weight: "250g",
      features: [
        "Active Noise Cancellation",
        "Touch Controls",
        "Multipoint Bluetooth",
        "Fast Charging",
      ],
    },
  },

  // 5 Monitor
  {
    title: "Samsung Odyssey G5",
    slug: "samsung-odyssey-g5",
    description:
      "Curved gaming monitor with high refresh rate and smooth visuals.",
    key_features: ["144Hz Refresh Rate", "1ms Response Time", "Curved Display"],
    banner: "/products/monitor/monitor-image1.png",
    images: [
      "/products/monitor/monitor-image1.png",
      "/products/monitor/monitor-image2.png",
      "/products/monitor/monitor-image3.png",
    ],
    category: "monitor",
    brand: "Samsung",
    product_model: "Odyssey G5 LC27G55",
    price: 329.99,
    stock: 20,
    warranty: "1 Year Official",
    specs: {
      display: {
        size: "27 inch",
        type: "LED",
        panel_type: "VA",
        resolution: "2560x1440 (QHD)",
        aspect_ratio: "16:9",
        refresh_rate: "144Hz",
        response_time: "1ms",
        brightness: "300 nits",
        viewing_angle: {
          horizontal: "178°",
          vertical: "178°",
        },
        contrast_ratio_static: "2500:1",
        contrast_ratio_dynamic: "1000000:1",
        curvature: "1000R",
        color_support: "sRGB 99%",
      },
      audio: {
        speaker_built_in: false,
      },
      connectivity: {
        vga: null,
        hdmi: "2 x HDMI 2.0",
        display_port: "1 x DisplayPort 1.2",
      },
      physical: {
        vesa_wall_mount: true,
        color: "Black",
        weight: "4.5kg",
      },
    },
  },

  // 6 Smart Watch
  {
    title: "COLMI P71 Smart Watch",
    slug: "colmi-p71-smart-watch",
    description:
      "Smartwatch with 1.9-inch IPS HD display, Bluetooth calling, heart rate monitoring, SpO2 tracking, 104 sport modes, and IP68 waterproof rating.",
    key_features: [
      "1.9 inch IPS HD Display",
      "Bluetooth Calling",
      "Heart Rate & SpO2 Monitoring",
      "104 Sports Modes",
      "IP68 Waterproof",
    ],
    banner: "/products/smart-watch/smart-watch-image1.png",
    images: [
      "/products/smart-watch/smart-watch-image1.png",
      "/products/smart-watch/smart-watch-image2.png",
      "/products/smart-watch/smart-watch-image3.png",
    ],
    category: "smart_watch",
    brand: "COLMI",
    product_model: "P71",
    price: 1480,
    stock: 50,
    warranty: "6 Months",
    specs: {
      display: {
        size: "1.9 inch",
        display_type: "IPS HD",
        resolution: "240x286 pixels",
      },
      processor: "RTL8763EWE",
      battery: {
        capacity: "230mAh",
      },
      connectivity: {
        bluetooth: "Bluetooth 5.1",
        bluetooth_calling: true,
      },
      health_tracking: {
        heart_rate: true,
        spo2: true,
      },
      sports_modes: 104,
      waterproof: "IP68",
      compatible_os: ["Android 4.4+", "iOS 8.0+", "HarmonyOS"],
      sensors: ["VP60A HR Sensor"],
      languages: [
        "Simplified Chinese",
        "English",
        "German",
        "Japanese",
        "Spanish",
        "Italian",
        "French",
        "Greek",
        "Dutch",
        "Portuguese",
        "Russian",
        "Turkish",
        "Korean",
        "Polish",
        "Romanian",
        "Thai",
        "Vietnamese",
        "Indonesian",
        "Hebrew",
        "Malaysian Malay",
        "Ukrainian",
      ],
      materials: {
        case: "ABS+PC",
        strap: "Silicone",
      },
      features: [
        "Bluetooth calling",
        "Heart rate monitoring",
        "SpO2 tracking",
        "Multiple sport modes",
        "Built-in games",
        "Calculator",
        "IP68 waterproof",
      ],
    },
  },

  // 7 Processor
  {
    title: "Intel Core i9-13900K",
    slug: "intel-core-i9-13900k",
    description:
      "13th Gen Intel Core processor with high performance for gaming and content creation.",
    key_features: [
      "24 Cores (8 Performance + 16 Efficient)",
      "32 Threads",
      "Supports DDR5-5600 & DDR4-3200",
      "Integrated Intel UHD Graphics 770",
    ],
    banner: "/products/processor/processor-image.png",
    images: ["/products/processor/processor-image.png", ,],
    category: "processor",
    brand: "Intel",
    product_model: "i9-13900K",
    price: 699.99,
    stock: 15,
    warranty: "3 Years",
    specs: {
      clock_speed: {
        base: "3.0 GHz",
        boost: "5.8 GHz",
      },
      cores: 24,
      threads: 32,
      cache: {
        l2: "32MB",
        l3: "36MB",
      },
      socket: "LGA1700",
      tdp: "125W",
      memory_support: {
        memory_type: "DDR5",
        max_size: "128GB",
        max_speed: ["5200 MHz", "5600 MHz"],
        channels: 2,
      },
      graphics: {
        integrated: true,
      },
    },
  },

  // 8 RAM
  {
    title: "Corsair Vengeance LPX",
    slug: "corsair-vengeance-lpx",
    description: "High-performance DDR4 RAM for gaming and overclocking.",
    key_features: [
      "High-speed DDR4",
      "Low profile heat spreader",
      "Overclockable",
    ],
    banner: "/products/ram/ram-image.png",
    images: ["/products/ram/ram-image.png"],
    category: "ram",
    brand: "Corsair",
    product_model: "Vengeance LPX 16GB",
    price: 89.99,
    stock: 60,
    warranty: "1 Year Official",
    specs: {
      ram_type: "DDR4",
      capacity: "16GB",
      frequency: "3200MHz",
      voltage: "1.35V",
      latency: "CL16",
      bandwidth: "25.6 GB/s",
      pin: 288,
      heat_spreader: "Aluminum",
      dimensions: "133.35 x 30 x 7 mm",
      rgb: false,
      features: ["Overclockable", "Low profile"],
    },
  },
];
