import Banner from "@/components/pages/home/banner/Banner";
import BrandsSections from "@/components/pages/home/BrandsSections";
import CategorySection from "@/components/pages/home/CategorySection";
import FeaturesSection from "@/components/pages/home/FeaturesSection";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tech Trade | Landing Page",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <>
    <section className="space-y-8">
      <Banner/>
      <CategorySection/>
      <FeaturesSection/>
      <BrandsSections/>
    </section>
    </>
  );
}
